name: swoole-compiler
type: bin
version: 0.1.0
cxxflags: |
  -std=c++14
  -Wall
sources:
  - ./src/Php
  - ./src/Core
  - ./src/functions.php
  - ./src/gen_stub.php
  - ./src/compiler-build.php
  - vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php
  - vendor/nikic/php-parser/lib/PhpParser/NodeVisitorAbstract.php
