name: swoole-compiler
build-mode: bin
version: 0.1.0
cxx-std: c++14
cxx-flags:
  - -Wall

sources:
  - ./src/Php
  - ./src/Core
  - ./src/functions.php
  - ./src/gen_stub.php
  - ./src/compiler-build.php
  - vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php
  - vendor/nikic/php-parser/lib/PhpParser/NodeVisitorAbstract.php
